@baseUrl = http://localhost:3333
@authToken = {{authentication.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Giovanne Soares",
  "email": "giovannesoares@dev.com",
  "password": "1234"
}

###
# @name authentication
POST {{baseUrl}}/sessions
Content-Type: application/json

{
 "email": "giovanne@dev.com",
  "password": "1234"
}


###
# @name create_question
POST {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova Pergunta03",
  "content": "Conteúdo da pergunta03"
}

###
# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
